ride_hailing:


  target: dev
  outputs:
    dev:
      type: postgres
      host: ep-wispy-queen-aytzc1lh.c-5.us-east-2.aws.neon.tech
      user: dev_abdelrahman
      password: "abdelrahman@2026"
      port: 5432
      dbname: neondb
      schema: dbt_dev
      threads: 4
      sslmode: require